import 'package:get/get.dart';

class LocaleString extends Translations {
@override
Map<String, Map<String, String>> get keys => {
'tr_TR': {
'Ana Sayfa': 'Ana Sayfa',
'BKİ': 'Beden Kütle İndeksi',
'İdeal Kilo': 'ideak kilo',
'Yağsız Vücut Ağırlığı': 'Yağsız Vücut Ağırlığı',
'Vücut Yağ Ağırlığı': 'Vücut Yağ Ağırlığı',
'Yüzey Alanı': 'Yüzey Alanı',
'Bazal Metabolizma': 'Bazal Metabolizma',
'Kan Volümü': 'Kan Volümü',
'ana ekran yazısı': 'Bilgilerim kısmına giderek daha detaylı kişisel sağlık bilgilerinizi hesaplayabilirsiniz.',
'(kcal/gün)': '(kcal/gün)',
'Bilgilerim': 'Bilgilerim',
'Hesaplamalar': 'Hesaplamalar',
'Bel Çevresi': 'Bel Çevresi',
'Dil': 'Dil',
'Dil Değiştir': 'Dil Değiştir',
'Tema': 'Tema',
'Kişisel Bilgiler': 'Kişisel Bilgiler',
'Doğum Tarihinizi Giriniz': 'Doğum Tarihinizi Giriniz',
'Yaş': 'Yaş',
'Boy': 'Boy',
'Kilo': 'Kilo',
'Lütfen bir dil seçiniz': 'Lütfen bir dil seçiniz',
'Sonuç': 'Sonuç',
'Hesapla': 'Hesapla',
'Aşırı Düşük Kilolu': 'Aşırı Düşük Kilolu',
'Çok Düşük Kilolu': 'Çok Düşük Kilolu',
'Düşük Kilolu': 'Düşük Kilolu',
'Normal': 'Normal',
'Fazla Kilolu': 'Fazla Kilolu',
'Şişman (Obez) - I. Sınıf': 'Şişman (Obez) - I. Sınıf',
'Şişman (Obez) - II. Sınıf': 'Şişman (Obez) - II. Sınıf',
'Aşırı Şişman (Aşırı Obez) - III. Sınıf': 'Aşırı Şişman (Aşırı Obez) - III. Sınıf',
'getTitle1': 'Boyunuza göre uygun ağırlıkta olmadığınızı, zayıf olduğunuzu gösterir. Zayıflık, bazı hastalıklar için risk oluşturan ve istenmeyen bir durumdur. Boyunuza uygun ağırlığa erişmeniz için yeterli ve dengeli beslenmeli, beslenme alışkanlıklarınızı geliştirmeye özen göstermelisiniz.',
'getTitle2': 'Boyunuza göre uygun ağırlıkta olduğunuzu gösterir. Yeterli ve dengeli beslenerek ve düzenli fiziksel aktivite yaparak bu ağırlığınızı korumaya özen gösteriniz.',
'getTitle3': 'Boyunuza göre vücut ağırlığınızın fazla olduğunu gösterir. Fazla kilolu olma durumu gerekli önlemler alınmadığı takdirde pek çok hastalık için risk faktörü olan obeziteye (şişmanlık) yol açar.',
'getTitle4': 'Boyunuza göre vücut ağırlığınızın fazla olduğunu bir başka deyişle şişman olduğunuzun bir göstergesidir. Şişmanlık, kalp-damar hastalıkları, diyabet, hipertansiyon v.b. kronik hastalıklar için risk faktörüdür. Bir sağlık kuruluşuna başvurarak hekim / diyetisyen kontrolünde zayıflayarak normal ağırlığa inmeniz sağlığınız açısından çok önemlidir. Lütfen, sağlık kuruluşuna başvurunuz.',
'Artmış Risk': 'Artmış Risk',
'Yüksek Risk': 'Yüksek Risk',
'Sorun Oluştu': 'Sorun Oluştu',
'waistMid1': 'Erkeklerin bel çevresinin 94cm den büyük olması risklidir. Yeterli ve dengeli beslenerek, düzenli fiziksel aktivite yaparak boyunuza uygun ağırlığa ulaşmaya özen gösterin.',
'waistMid2': 'Erkeklerin bel çevresinin 102cm den büyük olması şişmanlığın göstergesidir. Bu sağlığınız için risklidir. Lütfen bir sağlık kuruluşuna başvurunuz.',
'waistMid3': 'Erkeklerin bel çevresinin 94cm den küçük olması normaldir.Yeterli ve dengeli beslenerek, düzenli aktivite yaparak formunuzu korumaya özen gösterin.',
'waistMid4': 'Kadınların bel çevresinin 80cm den büyük olması risklidir. Yeterli ve dengeli beslenerek, düzenli fiziksel aktivite yaparak boyunuza uygun ağırlığa ulaşmaya özen gösterin.',
'waistMid5': 'Kadınların bel çevresinin 88cm den büyük olması şişmanlığın göstergesidir. Bu sağlığınız için risklidir. Lütfen bir sağlık kuruluşuna başvurunuz.',
'waistMid6': 'Kadınların bel çevresinin 80cm den küçük olması normaldir.Yeterli ve dengeli beslenerek, düzenli aktivite yaparak formunuzu korumaya özen gösterin.',
'Bel Çevresi Hesaplama': 'Bel Çevresi Hesaplama',
'Arkadaş Ekle': 'Arkadaş Ekle',
'Arkadaşlar': 'Arkadaşlar',
'Günlük Kilo Takibi': 'Günlük Kilo Takibi',
'Kilo Geçmişi': 'Kilo Geçmişi',
'Grafik Sonuçları': 'Grafik Sonuçları',
'Günlük Sonuçlar': 'Günlük Sonuçlar',
'Haftalık Sonuçlar': 'Haftalık Sonuçlar',
'Vücut Bilgileri': 'Vücut Bilgileri',
'Merhaba': 'Merhaba',
'Haftalık Grafik': 'Haftalık Grafik',
'Hedef Kilo': 'Hedef Kilo',
'Ayarlar': 'Ayarlar',
'Profil': 'Profil',
'Kullanıcı Adınız: ': 'Kullanıcı Adınız: ',
'Diğer kullanıcılardan arkadaşlık isteği alınsın mı?': 'Diğer kullanıcılardan arkadaşlık isteği alınsın mı?',
'Bilgilerin arkadaşlarınla paylaşılsın mı?': 'Bilgilerin arkadaşlarınla paylaşılsın mı?',
'Galeri': 'Galeri',
'Kamera': 'Kamera',
'Dikkat!': 'Dikkat!',
'Telefon numarası eklemek veya değiştirmek istediğine emin misin?': 'Telefon numarası eklemek veya değiştirmek istediğine emin misin?',
'Telefon Numaranız': 'Telefon Numaranız',
'Vazgeç': 'Vazgeç',
'Kaydet': 'Kaydet',
},



'en_US': {
'Ana Sayfa': 'Home Page',
'BKİ': 'Body Mass Index',
'İdeal Kilo': 'Ideal Weight',
'Yağsız Vücut Ağırlığı': 'Lean Body Weight',
'Vücut Yağ Ağırlığı': 'Body Fat Weight',
'Yüzey Alanı': 'Surface Area',
'Bazal Metabolizma': 'Basal Metabolism',
'Kan Volümü': 'Blood Volume',
'ana ekran yazısı': 'Information about information can calculate personal personal personal information.',
'(kcal/gün)': '(kcal/day)',
'Bilgilerim': 'My Information',
'Hesaplamalar': 'Calculations',
'Bel Çevresi': 'Waist Circumference',
'Dil': 'Language',
'Dil Değiştir': 'Change language',
'Tema': 'Theme',
'Kişisel Bilgiler': 'Personal Information',
'Doğum Tarihinizi Giriniz': 'Enter Your Date of Birth',
'Yaş': 'Age',
'Boy': 'Height',
'Kilo': 'Weight',
'Lütfen bir dil seçiniz': 'Please select a language',
'Sonuç': 'Result',
'Hesapla': 'Calculate',
'Aşırı Düşük Kilolu': 'Extremely Underweight',
'Çok Düşük Kilolu': 'Very Underweight',
'Düşük Kilolu': 'Low Weight',
'Normal': 'Normal',
'Fazla Kilolu': 'Overweight',
'Şişman (Obez) - I. Sınıf': 'Fat (Obese) - Class I',
'Şişman (Obez) - II. Sınıf': 'Fat (Obese) - II. Class',
'Aşırı Şişman (Aşırı Obez) - III. Sınıf': 'Extremely Obese (Extremely Obese) - III. Class',
'getTitle1': 'It shows that you are not at the appropriate weight for your height, you are weak. Weakness is an undesirable condition that poses a risk for some diseases. In order to reach a weight suitable for your height, you should eat adequate and balanced nutrition and take care to improve your eating habits.',
'getTitle2': 'Indicates that you are the appropriate weight for your height. Take care to maintain this weight by eating adequate and balanced nutrition and doing regular physical activity.',
'getTitle3': 'It indicates that your body weight is more than your height. Being overweight leads to obesity, which is a risk factor for many diseases, unless necessary precautions are taken.',
'getTitle4': 'It is an indication that your body weight is more than your height, in other words, that you are fat. Obesity, cardiovascular diseases, diabetes, hypertension etc. is a risk factor for chronic diseases. It is very important for your health that you go to a normal weight by weakening under the control of a physician / dietitian by applying to a health institution. Please, apply to the health institution.',
'Artmış Risk': 'Increased Risk',
'Yüksek Risk': 'High Risk',
'Sorun Oluştu': 'The Problem Has Occurred',
'waistMid1': 'It is risky for men to have a waist circumference greater than 94 cm. Take care to reach the appropriate weight for your height by eating adequate and balanced diet and doing regular physical activity.',
'waistMid2': 'A mens waist circumference greater than 102 cm is an indicator of obesity. This is risky for your health. Please consult a health institution.',
'waistMid3': 'It is normal for men to have a waist circumference of less than 94 cm. Take care to maintain your form by eating adequate and balanced nutrition and doing regular activities.',
'waistMid4': 'Womens waist circumference greater than 80 cm is risky. Take care to reach the appropriate weight for your height by eating adequate and balanced diet and doing regular physical activity.',
'waistMid5': 'Womens waist circumference greater than 88 cm is an indicator of obesity. This is risky for your health. Please consult a health institution.',
'waistMid6': 'It is normal for women to have a waist circumference of less than 80 cm. Take care to maintain your form by eating a sufficient and balanced diet and doing regular activities.',
'Bel Çevresi Hesaplama': 'Waist Circumference Calculator',
'Yükleniyor...': 'Loading...',
'Arkadaş Ekle': 'Add to Friend',
'Arkadaşlar': 'Friends',
'Günlük Kilo Takibi': 'Daily Weight Tracker',
'Kilo Geçmişi': 'Weight History',
'Grafik Sonuçları': 'Graph Results',
'Günlük Sonuçlar': 'Daily Results',
'Haftalık Sonuçlar': 'Weekly Results',
'Vücut Bilgileri': 'Body Information',
'Merhaba': 'Hello',
'Haftalık Grafik': 'Weekly Chart',
'Hedef Kilo': 'Target Weight',
'Ayarlar': 'Settings',
'Profil': 'Profile',
'Kullanıcı Adınız: ': 'Username: ',
'Diğer kullanıcılardan arkadaşlık isteği alınsın mı?': 'Do you want to receive friend requests from other users?',
'Bilgilerin arkadaşlarınla paylaşılsın mı?': 'Would you like to share your information with your friends?',
'Galeri': 'Gallery',
'Kamera': 'Camera',
'Dikkat!': 'Attention!',
'Telefon numarası eklemek veya değiştirmek istediğine emin misin?': 'Are you sure you want to add or change a phone number?',
'Telefon Numaranız': 'Your telephone number',
'Vazgeç': 'Cancel',
'Kaydet': 'Save',
},
};}
